### ISSUE TITLE
Can you add instructions for local installation?

### ISSUE THREAD

**Issue by MeGA-ct** [raidensakura/hoyolab-auto-login#10]
Hi 

I have linux machine that I use as home server, and I'd rather use it than use those external services.

Thx.

**Comment by Golumpa** [comment]
> Hi
> 
> I have linux machine that I use as home server, and I'd rather use it than use those external services.
> 
> Thx.

For the best results use the docker image if your going to self host like I do,
https://github.com/raidensakura/hoyolab-auto-login/pkgs/container/hoyolab-auto-login

**Comment by MeGA-ct** [comment]
Ok, thank you.

**Comment by MeGA-ct** [comment]
Sorry to reopen this, but I noticed that I can't find how to configure Variables for the Docker Image.

Or are those just System wide variables?

**Comment by MeGA-ct** [comment]
Sorry about reopening this,

I seems that I can't find where to create the Variables for the Docker image to use.

Or are just system wide variables?

Thx again.

**Comment by MeGA-ct** [comment]
Well I found the .env.example and tried to run it with (with my data)
`docker run -i -t --env-file ~/.env_hoyologin`
And it worked.

Sorry for any inconvenience, and Thanks again.
