### ISSUE TITLE
Obtaining cookie for "ltuid_v2" accounts.

### ISSUE THREAD

**Issue by Nixeld** [raidensakura/hoyolab-auto-login#16]
HoYoLAB has changed the tokens on July 2023, switching from the previous "ltoken" and "ltuid" to "ltoken_v2" and "ltuid_v2".

New accounts and accounts that has changed passwords recently are using the new tokens. 
HoYoLAB has changed the cookie to HttpOnly cookie. It is no longer possible to read the cookies by using `document.cookie` and will need to retrieve their cookie manually here.
![Untitled](https://github.com/raidensakura/hoyolab-auto-login/assets/18643932/287511c9-d5c7-4e75-acd4-7c80530c2b2d)

**Comment by raidensakura** [comment]
Fixed in 2843367.
