### ISSUE TITLE
Discord webhook fails if there's more than 10 embeds in a message

### ISSUE THREAD

**Issue by BuIlDaLiBlE** [raidensakura/hoyolab-auto-login#5]
```
[2023-06-17 17:47:19] [ERROR] Webhook status code 400: {"embeds": ["Must be 10 or fewer in length."]}
[2023-06-17 17:47:19] [ERROR] Sending embed failed: <Response [400]>
```
Embeds need to be sent either in their own message or by sending no more than 10 per message.

**Comment by raidensakura** [comment]
Will issue a fix when I'm available, thank you for the bug report (⊙Д⊙)

**Comment by BuIlDaLiBlE** [comment]
Thx for the quick response! My simple bash script stopped working for Genshin (they ask for captcha now), glad to see this still working.

**Comment by raidensakura** [comment]
> Thx for the quick response! My simple bash script stopped working for Genshin (they ask for captcha now), ~glad to see this still working~ nevermind that, due to captcha this does not work either. The server returns OK but it doesn't actually count towards the check-in.

I fixed embed problem but regarding the captcha problem I've opened [a different issue](https://github.com/raidensakura/hoyolab-auto-login/issues/6) since it's unrelated to this one. I'll be closing this as completed now.
