### ISSUE TITLE
Should the script auto-redeem game codes?

### ISSUE THREAD

**Issue by raidensakura** [raidensakura/hoyolab-auto-login#9]
Asking for feedback on whether we should implement code-redeeming functionality inside the script.

This will need a storage of some kind to store already-redeemed/invalid codes. I'm either thinking of using some kind of third-party pastebin service since I want the script to be immutable by not storing data locally. I'm considering using either [GitHub Gist](https://gist.github.com/) or [Rentry](https://rentry.co/) but suggestions are appreciated. 

Users would simply need to create a gist/rentry and add the auth token in the env variables for the script to fetch and edit the texts stored in it.

Let me know if this feature is needed and if there's a better way to implement it.

**Comment by Equ1no0x** [comment]
If you go through with the idea, a Pastebin sounds like an excellent location to grab codes from, but unless that Pastebin is also automated, it will still require someone to keep it up to date.

**Comment by AncientCatz** [comment]
Maybe you can see an example from this repo: https://github.com/c4em/collei
It fetches the redeem codes from the wiki: https://honkai-star-rail.fandom.com/wiki/Redemption_Code

**Comment by raidensakura** [comment]
Closing this as this doesn't seem possible as of now due to code redeem endpoints requiring `cookie_token_v2` which expires every few days, making automation impossible until I find a way to auto-refresh it without user input.

**Comment by raidensakura** [comment]
Closing this as this doesn't seem possible as of now due to code redeem endpoints requiring `cookie_token_v2` which expires every few days, making automation impossible until I find a way to auto-refresh it without user input.

**Comment by AncientCatz** [comment]
> Closing this as this doesn't seem possible as of now due to code redeem endpoints requiring `cookie_token_v2` which expires every few days, making automation impossible until I find a way to auto-refresh it without user input.

Maybe the easiest solution for now is an automatic reminder if there is a new redemption code via Discord.
